# fly.toml file generated for todobot on 2023-04-12T17:51:19+03:00

app = "todobot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  BOT_TOKEN='5817587141:AAGAS3At-3u6vvXqnB9O9DPGbllwK_uVY04'
  ALLOWED_HOSTS="https://todobydukhovich.fly.dev/"


